/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kvstore;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class KVStoreTest {
    @Test
    void appHasAGreeting() {

    }
}
